### ISSUE TITLE
Incorrect File Type Message

### ISSUE THREAD

**Issue by TurboTanker** [SzAmmi/musicXml2scratch#4]
Every time I use musicXml2scratch, a message pops up saying "Your file isn't a musicxml file," even though it is. I'm downloading the files from musescore, and they have the extension .mxl. Is this a bug in the software, or an issue with my computer?

**Comment by SzAmmi** [comment]
Thanks for reporting! I'll fix this soon, 'cause I have very important
exams now.

2015-10-11 23:42 GMT+02:00 NWalker1208 <notifications@github.com>:

> Every time I use musicXml2scratch, a message pops up saying "Your file
> isn't a musicxml file," even though it is. I'm downloading the files from
> musescore, and they have the extension .mxl. Is this a bug in the software,
> or an issue with my computer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SzAmmi/musicXml2scratch/issues/4>.
>



-- 
Pozdrawiam,
Szymon Marczak

**Comment by SzAmmi** [comment]
@TurboTanker Sorry for very very late reply. I :'( :'( It's fixed now.
