### ISSUE TITLE
Syntax Error In Code

### ISSUE THREAD

**Issue by TurboTanker** [SzAmmi/musicXml2scratch#6]
In your index.html file, one of your script elements looks like this:
\<script\>
	\</body\>
\</html\>
\</script\>
This was likely a copy and paste mistake. Also, when I click the "start" button, an error comes up in the console saying "Uncaught ReferenceError: start is not defined." That function was likely meant to be defined in the script shown above.

Edit: When I have time, I will write a pull request

**Comment by SzAmmi** [comment]
Ok.

**Comment by SzAmmi** [comment]
Fixed. I'm closing this issue.
